### ISSUE TITLE
Frame description and temporal modeling

### ISSUE THREAD

**Issue by Zeyu1226-mt** [alibaba-mmai-research/TAdaConv#12]
Hello, very meaningful work. And I have some questions, thank you :
1. How do I understand frame description?  
2. Why can temporal modeling be realized through dimension reduction and expansion (that is, two-layer 1D convolution)?

**Comment by huang-ziyuan** [comment]
Hi, sorry for the delayed reply. 

1. The frame description is simply the global average pooled feature of each frame. Because it covers the whole frame, we understand it as the vector that describes the frame. 
2. The temporal modeling is mainly realised through the interaction between the frame descriptors. The important thing about this 1D convolution is that it has to cover more than one frame descriptors. :)
