### ISSUE TITLE
TAdaConv2d needs in_channels to equal out_channels

### ISSUE THREAD

**Issue by akanuasiegbu** [alibaba-mmai-research/TAdaConv#19]
Hi, this work seems interesting! Im trying to integrate TAdaConv2d into a different network , it seems like TAdaConv2d only works when the in_channels and the out_channels are set to be the same. Was this set (in_channels=out_channels) because of some particular reason ?

**Comment by huang-ziyuan** [comment]
Hi, thanks for your interest in TAdaConv. Since most of the convolutions (with kernel size other than 1x1) have the same input and output dimensions, we didn't try to add the support for cases with different input and output dimensions. But you are welcome to try. 

The thing you have to look out is that TAdaConv uses grouped convolutions to process batched inputs, and if you are applying TAdaConv to convolutions with different input and output dimensions, you will have to carefully modify this line https://github.com/alibaba-mmai-research/TAdaConv/blob/75b7839b37fc94d98d4fe5f2aff4b3df4e347dfb/tadaconv/models/module_zoo/ops/tadaconv.py#L146C9-L146C9. :)
