### ISSUE TITLE
Issue on running on sthv2

### ISSUE THREAD

**Issue by jwfanDL** [alibaba-mmai-research/TAdaConv#4]
Hi @huang-ziyuan 
We meet problems when running the script on something.
Some abstract methods may not be implemented in somethingv2 dataset class.
The error is shown as below:
![截屏2022-02-21 下午8 12 54](https://user-images.githubusercontent.com/49198978/154953430-0573acda-1d21-43d7-a3e2-8ce637682530.png)

**Comment by huang-ziyuan** [comment]
It seems to be the problem with PyTorch version later than 1.8.0. These abstract methods are fine without implementation in PyTorch 1.7.1 and before. A quick solution would be to implement the abstract methods to return None, since they are not used in the current version. We will update the code to fit for later versions soon.

**Comment by jwfanDL** [comment]
Thank you so much. We have solved this problem according your instructions.~
